name: CI

on:
  push:
    branches: [ main ] # Executa ao fazer push na branch main
  pull_request:
    branches: [ main ] # Executa ao criar PR para a branch main

jobs:
  build:
    runs-on: ubuntu-latest # Define o sistema operacional

    steps:
      - uses: actions/checkout@v3 # Faz checkout do código

      - name: Executar testes
        run: |
          echo "Nenhum teste implementado ainda. Adicione testes em script.js!"
          echo "Podemos adicionar testes com Jest ou Cypress no futuro."
          echo "Testes simulados aprovados"
          exit 0

      - name: Deploy para GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v2
        with:
          folder: . # Diretório a ser deployado (raiz do projeto)
